spring.application.name=atenciones

spring.datasource.url=jdbc:h2:file:./data/hospital
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


# spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# spring.datasource.url=jdbc:oracle:thin:@FPSDTP51J4RYAQY7_high?TNS_ADMIN=C:/Users/cassl/OneDrive/Documents/Code/wallet
# spring.datasource.username=admin
# spring.datasource.password=Monito1209$$
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
